// Package envfile reads and writes the installer's .env file, preserving
// comments/ordering as much as reasonably possible. Ported from env_set in
// lib/common.sh, extended with a batch Set + typed Load for the Go wizard.
package envfile

import (
	"bufio"
	"os"
	"sort"
	"strings"
)

// File is an in-memory view of a KEY=VALUE env file.
type File struct {
	path  string
	order []string
	vals  map[string]string
}

// Load reads path if it exists; a missing file yields an empty File.
func Load(path string) (*File, error) {
	f := &File{path: path, vals: map[string]string{}}
	data, err := os.ReadFile(path)
	if os.IsNotExist(err) {
		return f, nil
	}
	if err != nil {
		return nil, err
	}
	sc := bufio.NewScanner(strings.NewReader(string(data)))
	for sc.Scan() {
		line := sc.Text()
		trimmed := strings.TrimSpace(line)
		if trimmed == "" || strings.HasPrefix(trimmed, "#") {
			continue
		}
		eq := strings.Index(trimmed, "=")
		if eq <= 0 {
			continue
		}
		key := strings.TrimSpace(trimmed[:eq])
		val := unquoteShellValue(strings.TrimSpace(trimmed[eq+1:]))
		if _, exists := f.vals[key]; !exists {
			f.order = append(f.order, key)
		}
		f.vals[key] = val
	}
	return f, nil
}

// Get returns the value for key, or def if unset/empty.
func (f *File) Get(key, def string) string {
	if v, ok := f.vals[key]; ok && v != "" {
		return v
	}
	return def
}

// Set stages a key/value pair for the next Save.
func (f *File) Set(key, val string) {
	if _, exists := f.vals[key]; !exists {
		f.order = append(f.order, key)
	}
	f.vals[key] = val
}

// SetAll is a convenience wrapper around repeated Set calls. Keys are
// applied in sorted order so the resulting file is deterministic across
// runs (Go map iteration order is randomized).
func (f *File) SetAll(kv map[string]string) {
	keys := make([]string, 0, len(kv))
	for k := range kv {
		keys = append(keys, k)
	}
	sort.Strings(keys)
	for _, k := range keys {
		f.Set(k, kv[k])
	}
}

// Save writes the file back out, one KEY="VALUE" per line, insertion order.
// Values are always double-quoted and escaped: up.sh and friends `source`
// this file, so an unquoted value containing spaces (e.g. ENABLED_MODULES,
// a space-separated module list) would otherwise be parsed as a command.
func (f *File) Save() error {
	var b strings.Builder
	b.WriteString("# Generated by muxcore-setup — local install defaults.\n")
	for _, k := range f.order {
		b.WriteString(k)
		b.WriteByte('=')
		b.WriteString(quoteShellValue(f.vals[k]))
		b.WriteByte('\n')
	}
	tmp := f.path + ".tmp"
	if err := os.WriteFile(tmp, []byte(b.String()), 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, f.path)
}

// quoteShellValue wraps v in double quotes, escaping the characters that
// matter inside a double-quoted bash string ($ ` " \).
func quoteShellValue(v string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range v {
		switch r {
		case '\\', '$', '`', '"':
			b.WriteByte('\\')
		}
		b.WriteRune(r)
	}
	b.WriteByte('"')
	return b.String()
}

// unquoteShellValue strips a single layer of surrounding double or single
// quotes, undoing quoteShellValue (and tolerating hand-edited plain values).
func unquoteShellValue(v string) string {
	if len(v) >= 2 && v[0] == '"' && v[len(v)-1] == '"' {
		inner := v[1 : len(v)-1]
		var b strings.Builder
		for i := 0; i < len(inner); i++ {
			if inner[i] == '\\' && i+1 < len(inner) {
				switch inner[i+1] {
				case '\\', '$', '`', '"':
					i++
				}
			}
			b.WriteByte(inner[i])
		}
		return b.String()
	}
	if len(v) >= 2 && v[0] == '\'' && v[len(v)-1] == '\'' {
		return v[1 : len(v)-1]
	}
	return v
}

// AsMap returns a copy of every key/value currently staged.
func (f *File) AsMap() map[string]string {
	out := make(map[string]string, len(f.vals))
	for k, v := range f.vals {
		out[k] = v
	}
	return out
}
